Disc 92 license return non access ids
kb-dk/ds-license pull request #11
Opened 2023-10-04 10:52 UTC by thomasegense

When filtering Id's (normal ID field or resource-ID field), also return ID's that does exist, but where access was not allowed.

Here is a call to devel11 that shows the new output. 
There are 3 resource ID's in the input. 1) does not exist, 2) does exist and access, **3) no access but does exist.**

curl -X POST "http://devel11:10001/ds-license/v1/checkAccessForResourceIds" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"presentationType\":\"Search\",\"accessIds\":[\"id1\",\"/DAMJP2/DAM/Samlingsbilleder/0000/750/978/DNF_1955-00298_00092\",\"/DAMJP2/DAM/Samlingsbilleder/0000/532/736/KHP0147_26_037\"],\"attributes\":[{\"attribute\":\"everybody\",\"values\":[\"yes\"]}]}"

2023-10-04 13:10 UTC, tokee requested changes
From a functional point of view the code seems to do as intended. The extended response is directly usable by the frontend.

The comments in this pull request are on
1. Javadoc
2. Logging
3. Code structure

And an idea at the last moment: How about adding a third list of IDs: Non-existing? That way the caller has easy access to all IDs in all possible states.

2023-10-05 08:22 UTC, thomasegense reviewed
Changes from review:
    
    1) Added list of non-existing IDs to output
    2) refactoring
    3) some javadoc
    4) refactoring retailAll method so it is done in solr method so all
    callers does have to have do it.

2023-10-05 12:05 UTC, tokee commented on src/main/java/dk/kb/license/solr/AbstractSolrJClient.java
>          log.info("response:"+response);
The `log.info`-thing is also prevalent in `LicenseValidator`.

2023-10-05 12:06 UTC, tokee commented on src/main/java/dk/kb/license/validation/LicenseValidator.java
> +    //TODO shitload of javadoc
This means: Please write JavaDocs for all public methods that are `public` and non-trivial get/set/Override.

2023-10-05 13:06 UTC, thomasegense commented on src/main/java/dk/kb/license/validation/LicenseValidator.java
> +    //TODO shitload of javadoc
This metode is back when module was ported and there it was agreed to spent time javadoc'ing all methods. 
Instead spending time on the open API+module documentation.

2023-10-05 13:07 UTC, thomasegense commented on src/main/java/dk/kb/license/validation/LicenseValidator.java
> +        log.info("checkAccessForResourceID callled for presentationtype:"+input.getPresentationType());
Changed to debug, it is spammy but very useful in this phase of the project to figure out why it does not behave as expected.

2023-10-05 13:12 UTC, thomasegense commented on src/main/java/dk/kb/license/validation/LicenseValidator.java
>              throw new InvalidArgumentServiceException("Security problem: More Id's in output than input. Check for query injection.");
Log on warn now,  but method  also not part of this PR.

2023-10-05 13:23 UTC, thomasegense commented on src/main/java/dk/kb/license/validation/LicenseValidator.java
> +    }
Missed that comment. Is fixed now.

2023-10-05 13:25 UTC, thomasegense commented on src/main/java/dk/kb/license/solr/AbstractSolrJClient.java
>          log.info("response:"+response);
Did a little more clearing. I am pleased with the  ds-license.log on devel11 for now. 
Some of the spammy changed to debug

2023-10-05 14:22 UTC, tokee commented on src/main/java/dk/kb/license/validation/LicenseValidator.java
> +    //TODO shitload of javadoc
Grudgingly accepted.

2023-10-05 14:29 UTC, tokee commented on src/main/java/dk/kb/license/validation/LicenseValidator.java
> +    }
The method is more generic now, but the code at lines 108-122 are the same as before.

If you add `queryPartAccess` as a parameter to `filterResourceIDsThatExists`, the lines 108-122 can be replaced with a single call to the method.

2023-10-06 05:30 UTC, thomasegense commented on src/main/java/dk/kb/license/validation/LicenseValidator.java
> +    }
I was totally blind to this! Is fixed now. Obvious refactoring stuff..

2023-10-06 07:32 UTC, merged