Disc 281 clean exceptions
kb-dk/ds-license pull request #15
Opened 2023-12-12 15:24 UTC by VictorHarbo

Intellij code inspections are awesome. Besides fixking eceptions this PR also removes unused imports and fixes direct errors in javadocs

2023-12-12 16:26 UTC, tokee requested changes
All `throws`-changes are good, but narrowing `catch` is more tricky as `RuntimeExceptions` can happen "everywhere". Comments are about where the narrowed `catch`es should be changed back to `catch (Exception e)`.

2023-12-12 16:26 UTC, tokee commented on src/main/java/dk/kb/license/servlets/ConfigurationServlet.java
> +        } catch (NumberFormatException e) {//various server errors
The `NumberFormatException` does not seem to be thrown here? This seems like a case of "whatever unexpected happens, log it and report the error", so the previous `catch (Exception e)` was fine.

2023-12-12 16:26 UTC, tokee commented on src/main/java/dk/kb/license/webservice/ContextListener.java
> +       catch(SQLException e) {
This changes behaviour as `RuntimeException`s are no longer caught. The `H2DbUtil.createEmptyH2DBFromDDL` throws a `RuntimeException` if the DLL script cannot be found (which should have been a `FileNotFoundException`, but the point stands).

2023-12-12 16:26 UTC, tokee commented on src/main/java/dk/kb/license/Util.java
>  			log.info("Invalid dateformat entered:" + dateFormat);
Sigh. We need another JIRA on log levels. But I digress.

2023-12-18 07:14 UTC, VictorHarbo commented on src/main/java/dk/kb/license/servlets/ConfigurationServlet.java
> +        } catch (NumberFormatException e) {//various server errors
I'll change it back. This might be an example of where intelliJs inspections are not 100% on point as my IDE wants to change the broad exception to the NumberFormatException

2023-12-18 07:21 UTC, merged