Dra 640 login keycloak oath
kb-dk/ds-license pull request #32
Opened 2024-06-03 10:34 UTC by thomasegense

See internal jira DRA-640 for information

2024-06-06 11:52 UTC, VictorHarbo requested changes
A few comments here and there. @davidgrove73 should probably give a more thorough review on the security of the implementation.

2024-06-06 11:52 UTC, VictorHarbo commented on src/main/java/dk/kb/license/util/OauthUtil.java
> +        var algo = Algorithm.RSA256(getRSAPublicKey(rsaPublicKeyBase64), null);
Should the type be Algorithm instead of var?

2024-06-06 12:07 UTC, thomasegense reviewed
Added comments.

2024-06-06 12:07 UTC, thomasegense commented on conf/ds-license-environment.yaml.SAMPLE
added.

2024-06-06 12:07 UTC, thomasegense commented on src/main/java/dk/kb/license/servlets/LoginCallbackServlet.java
> +        return;
Removed return

2024-06-06 12:07 UTC, thomasegense commented on src/main/java/dk/kb/license/servlets/LoginCallbackServlet.java
> +     */
Not much to describe. Is called by Tomcat automatic. All servlet doGet/doPost has this API.

2024-06-11 09:00 UTC, davidgrove73 approved these changes

2024-06-11 10:19 UTC, merged