Pakker klausulering
kb-dk/ds-license pull request #4
Opened 2022-10-25 11:42 UTC by thomasegense

Everything renamed from deny to restriction.
Groups can be:
1) pakke/packages
2)klausulering/restriction

Massive code changes
GUI changed
documentation changed
UML dokumentation changed
DB rename column

Can be tested on:
http://devel11:10001/ds-license/

2022-11-22 13:39 UTC, tokee requested changes
I have not done an in-depth review of the code, just looked at the changed, started the application and poked around in the GUI. Overall this matches well what we talked about with a nice split between `Pakker` and `Klausileringer`. Minor points only:

- I tried creating a license but got "License name/description too short or validTo/validFrom is invalid". Digging into the code I could see that the date format is `dd-MM-yyyy` (I tried with blank and with `yyyy-MM-dd`. Could you add the date format as a mouse-over text or include it in the error message?
- I tested with `jetty:run`. Could you please change the port from the defaule 808 to something else? Maybe 9076 as that fits with the other `ds-`projects?
- The `licensemodule_uml.png` still uses the old `denyGroup` althought the code has changed

2022-11-24 07:50 UTC, thomasegense commented on src/main/java/dk/kb/license/util/LicenseChangelogGenerator.java
> +        b.append("Deny group:"+g.isRestrictionGroup() +NEWLINE);
All fixed. Sorry about the date format... It was not me specification.. Today I would insist using yyyy-MM-dd

2022-11-24 13:15 UTC, tokee commented on src/main/java/dk/kb/license/util/LicenseChangelogGenerator.java
> +        b.append("Deny group:"+g.isRestrictionGroup() +NEWLINE);
Looks good now, thanks for the changes.

I took the liberty of committing `placeholder`s and `pattern`s for the `validFrom` and `validTo` form fields to the branch, so new the review is reversed :-)
 https://www.w3schools.com/TAGS/att_input_placeholder.asp 

If you don't like then, just revert the commit.

2022-11-24 13:15 UTC, tokee approved these changes

2022-11-25 09:15 UTC, merged